/* eslint-disable */
// identity-instrument v0.1.0 6a778e223f7c2709e3bbb34ac876f2fc25ee1b72
// --
// Code generated by Webrpc-gen@v0.31.2 with typescript generator. DO NOT EDIT.
//
// webrpc-gen -schema=identity-instrument.ridl -target=typescript -client -out=./clients/identity-instrument.gen.ts

// Webrpc description and code-gen version
export const WebrpcVersion = "v1"

// Schema version of your RIDL schema
export const WebrpcSchemaVersion = "v0.1.0"

// Schema hash generated from your RIDL schema
export const WebrpcSchemaHash = "6a778e223f7c2709e3bbb34ac876f2fc25ee1b72"

//
// Client interface
//

export interface IdentityInstrumentClient {
  commitVerifier(req: CommitVerifierRequest, headers?: object, signal?: AbortSignal): Promise<CommitVerifierResponse>

  completeAuth(req: CompleteAuthRequest, headers?: object, signal?: AbortSignal): Promise<CompleteAuthResponse>

  sign(req: SignRequest, headers?: object, signal?: AbortSignal): Promise<SignResponse>
}


//
// Schema types
//

export enum KeyType {
  WebCrypto_Secp256r1 = 'WebCrypto_Secp256r1',
  Ethereum_Secp256k1 = 'Ethereum_Secp256k1'
}

export enum IdentityType {
  Email = 'Email',
  OIDC = 'OIDC'
}

export enum AuthMode {
  OTP = 'OTP',
  IDToken = 'IDToken',
  AccessToken = 'AccessToken',
  AuthCode = 'AuthCode',
  AuthCodePKCE = 'AuthCodePKCE'
}

export interface CommitVerifierParams {
  scope?: string
  identityType: IdentityType
  authMode: AuthMode
  metadata: {[key: string]: string}
  handle?: string
  signer?: Key
}

export interface CompleteAuthParams {
  scope?: string
  identityType: IdentityType
  signerType: KeyType
  authMode: AuthMode
  verifier: string
  answer: string
  lifetime?: number
}

export interface SignParams {
  scope?: string
  signer: Key
  nonce: string
  digest: string
}

export interface Identity {
  type: IdentityType
  issuer: string
  subject: string
  email: string
}

export interface Key {
  keyType: KeyType
  address: string
}

export interface AuthID {
  scope: string
  authMode: AuthMode
  identityType: IdentityType
  verifier: string
}

export interface AuthKeyData {
  scope: string
  authKey: string
  signer: string
  expiry: string
}

export interface SignerData {
  scope: string
  identity: Identity
  keyType: KeyType
  privateKey: string
}

export interface AuthCommitmentData {
  scope: string
  authKey: string
  authMode: AuthMode
  identityType: IdentityType
  handle: string
  signer: string
  challenge: string
  answer: string
  metadata: {[key: string]: string}
  attempts: number
  expiry: string
}

export interface CommitVerifierRequest {
  params: CommitVerifierParams
  authKey: Key
  signature: string
}

export interface CommitVerifierResponse {
  verifier: string
  loginHint: string
  challenge: string
}

export interface CompleteAuthRequest {
  params: CompleteAuthParams
  authKey: Key
  signature: string
}

export interface CompleteAuthResponse {
  signer: Key
  identity: Identity
}

export interface SignRequest {
  params: SignParams
  authKey: Key
  signature: string
}

export interface SignResponse {
  signature: string
}



//
// Client
//

export class IdentityInstrument implements IdentityInstrumentClient {
  protected hostname: string
  protected fetch: Fetch
  protected path = '/rpc/IdentityInstrument/'

  constructor(hostname: string, fetch: Fetch) {
    this.hostname = hostname.replace(/\/*$/, '')
    this.fetch = (input: RequestInfo, init?: RequestInit) => fetch(input, init)
  }

  private url(name: string): string {
    return this.hostname + this.path + name
  }
  
  queryKey = {
    commitVerifier: (req: CommitVerifierRequest) => ['IdentityInstrument', 'commitVerifier', req] as const,
    completeAuth: (req: CompleteAuthRequest) => ['IdentityInstrument', 'completeAuth', req] as const,
    sign: (req: SignRequest) => ['IdentityInstrument', 'sign', req] as const,
  }

  commitVerifier = (req: CommitVerifierRequest, headers?: object, signal?: AbortSignal): Promise<CommitVerifierResponse> => {
    return this.fetch(
      this.url('CommitVerifier'),
      createHttpRequest(JsonEncode(req), headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<CommitVerifierResponse>(_data, 'CommitVerifierResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  completeAuth = (req: CompleteAuthRequest, headers?: object, signal?: AbortSignal): Promise<CompleteAuthResponse> => {
    return this.fetch(
      this.url('CompleteAuth'),
      createHttpRequest(JsonEncode(req), headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<CompleteAuthResponse>(_data, 'CompleteAuthResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  sign = (req: SignRequest, headers?: object, signal?: AbortSignal): Promise<SignResponse> => {
    return this.fetch(
      this.url('Sign'),
      createHttpRequest(JsonEncode(req), headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<SignResponse>(_data, 'SignResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

}

const createHttpRequest = (body: string = '{}', headers: object = {}, signal: AbortSignal | null = null): object => {
  const reqHeaders: { [key: string]: string } = { ...headers, 'Content-Type': 'application/json', [WebrpcHeader]: WebrpcHeaderValue }
  return { method: 'POST', headers: reqHeaders, body, signal }
}

const buildResponse = (res: Response): Promise<any> => {
  return res.text().then(text => {
    let data
    try {
      data = JSON.parse(text)
    } catch(error) {
      throw WebrpcBadResponseError.new({
        status: res.status,
        cause: `JSON.parse(): ${error instanceof Error ? error.message : String(error)}: response text: ${text}`},
      )
    }
    if (!res.ok) {
      const code: number = (typeof data.code === 'number') ? data.code : 0
      throw (webrpcErrorByCode[code] || WebrpcError).new(data)
    }
    return data
  })
}

export type Fetch = (input: RequestInfo, init?: RequestInit) => Promise<Response>






export const JsonEncode = <T = any>(obj: T): string => {
  return JSON.stringify(obj)
}

export const JsonDecode = <T = any>(data: string | any, _typ: string = ''): T => {
  let parsed: any = data
  if (typeof data === 'string') {
    try { parsed = JSON.parse(data) } catch (err) {
      throw WebrpcBadResponseError.new({ cause: `JsonDecode: JSON.parse failed: ${(err as Error).message}` })
    }
  }
  return parsed as T
}


//
// Errors
//

type WebrpcErrorParams = { name?: string, code?: number, message?: string, status?: number, cause?: string }

export class WebrpcError extends Error {
  code: number
  status: number

  constructor(error: WebrpcErrorParams = {}) {
    super(error.message)
    this.name = error.name || 'WebrpcEndpointError'
    this.code = typeof error.code === 'number' ? error.code : 0
    this.message = error.message || `endpoint error`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcError.prototype)
  }

  static new(payload: any): WebrpcError {
    return new this({ message: payload.message, code: payload.code, status: payload.status, cause: payload.cause })
  }
}


export class WebrpcEndpointError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcEndpoint'
    this.code = typeof error.code === 'number' ? error.code : 0
    this.message = error.message || `endpoint error`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcEndpointError.prototype)
  }
}

export class WebrpcRequestFailedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcRequestFailed'
    this.code = typeof error.code === 'number' ? error.code : -1
    this.message = error.message || `request failed`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcRequestFailedError.prototype)
  }
}

export class WebrpcBadRouteError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadRoute'
    this.code = typeof error.code === 'number' ? error.code : -2
    this.message = error.message || `bad route`
    this.status = typeof error.status === 'number' ? error.status : 404
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadRouteError.prototype)
  }
}

export class WebrpcBadMethodError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadMethod'
    this.code = typeof error.code === 'number' ? error.code : -3
    this.message = error.message || `bad method`
    this.status = typeof error.status === 'number' ? error.status : 405
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadMethodError.prototype)
  }
}

export class WebrpcBadRequestError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadRequest'
    this.code = typeof error.code === 'number' ? error.code : -4
    this.message = error.message || `bad request`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadRequestError.prototype)
  }
}

export class WebrpcBadResponseError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadResponse'
    this.code = typeof error.code === 'number' ? error.code : -5
    this.message = error.message || `bad response`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadResponseError.prototype)
  }
}

export class WebrpcServerPanicError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcServerPanic'
    this.code = typeof error.code === 'number' ? error.code : -6
    this.message = error.message || `server panic`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcServerPanicError.prototype)
  }
}

export class WebrpcInternalErrorError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcInternalError'
    this.code = typeof error.code === 'number' ? error.code : -7
    this.message = error.message || `internal error`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcInternalErrorError.prototype)
  }
}

export class WebrpcClientAbortedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcClientAborted'
    this.code = typeof error.code === 'number' ? error.code : -8
    this.message = error.message || `request aborted by client`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcClientAbortedError.prototype)
  }
}

export class WebrpcStreamLostError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcStreamLost'
    this.code = typeof error.code === 'number' ? error.code : -9
    this.message = error.message || `stream lost`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcStreamLostError.prototype)
  }
}

export class WebrpcStreamFinishedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcStreamFinished'
    this.code = typeof error.code === 'number' ? error.code : -10
    this.message = error.message || `stream finished`
    this.status = typeof error.status === 'number' ? error.status : 200
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcStreamFinishedError.prototype)
  }
}


//
// Schema errors
//

export class InternalErrorError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'InternalError'
    this.code = typeof error.code === 'number' ? error.code : 7100
    this.message = error.message || `Internal error`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, InternalErrorError.prototype)
  }
}

export class EncryptionErrorError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'EncryptionError'
    this.code = typeof error.code === 'number' ? error.code : 7101
    this.message = error.message || `Encryption error`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, EncryptionErrorError.prototype)
  }
}

export class DatabaseErrorError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'DatabaseError'
    this.code = typeof error.code === 'number' ? error.code : 7102
    this.message = error.message || `Database error`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, DatabaseErrorError.prototype)
  }
}

export class DataIntegrityErrorError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'DataIntegrityError'
    this.code = typeof error.code === 'number' ? error.code : 7103
    this.message = error.message || `Data integrity error`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, DataIntegrityErrorError.prototype)
  }
}

export class IdentityProviderErrorError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'IdentityProviderError'
    this.code = typeof error.code === 'number' ? error.code : 7104
    this.message = error.message || `Identity provider error`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, IdentityProviderErrorError.prototype)
  }
}

export class InvalidRequestError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'InvalidRequest'
    this.code = typeof error.code === 'number' ? error.code : 7200
    this.message = error.message || `The request was invalid`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, InvalidRequestError.prototype)
  }
}

export class InvalidSignatureError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'InvalidSignature'
    this.code = typeof error.code === 'number' ? error.code : 7201
    this.message = error.message || `The signature was invalid`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, InvalidSignatureError.prototype)
  }
}

export class KeyNotFoundError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'KeyNotFound'
    this.code = typeof error.code === 'number' ? error.code : 7202
    this.message = error.message || `The authentication key was not found`
    this.status = typeof error.status === 'number' ? error.status : 404
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, KeyNotFoundError.prototype)
  }
}

export class KeyExpiredError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'KeyExpired'
    this.code = typeof error.code === 'number' ? error.code : 7203
    this.message = error.message || `The authentication key expired`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, KeyExpiredError.prototype)
  }
}

export class SignerNotFoundError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'SignerNotFound'
    this.code = typeof error.code === 'number' ? error.code : 7204
    this.message = error.message || `The signer was not found`
    this.status = typeof error.status === 'number' ? error.status : 404
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, SignerNotFoundError.prototype)
  }
}

export class UsageLimitExceededError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'UsageLimitExceeded'
    this.code = typeof error.code === 'number' ? error.code : 7205
    this.message = error.message || `Too many requests`
    this.status = typeof error.status === 'number' ? error.status : 429
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, UsageLimitExceededError.prototype)
  }
}

export class PreconditionFailedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'PreconditionFailed'
    this.code = typeof error.code === 'number' ? error.code : 7206
    this.message = error.message || `Precondition failed; try again with a higher nonce value`
    this.status = typeof error.status === 'number' ? error.status : 412
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, PreconditionFailedError.prototype)
  }
}

export class ProofVerificationFailedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'ProofVerificationFailed'
    this.code = typeof error.code === 'number' ? error.code : 7002
    this.message = error.message || `The authentication proof could not be verified`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, ProofVerificationFailedError.prototype)
  }
}

export class AnswerIncorrectError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'AnswerIncorrect'
    this.code = typeof error.code === 'number' ? error.code : 7003
    this.message = error.message || `The provided answer is incorrect`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, AnswerIncorrectError.prototype)
  }
}

export class ChallengeExpiredError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'ChallengeExpired'
    this.code = typeof error.code === 'number' ? error.code : 7004
    this.message = error.message || `The challenge has expired`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, ChallengeExpiredError.prototype)
  }
}

export class TooManyAttemptsError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'TooManyAttempts'
    this.code = typeof error.code === 'number' ? error.code : 7005
    this.message = error.message || `Too many attempts`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, TooManyAttemptsError.prototype)
  }
}

export class OAuthErrorError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'OAuthError'
    this.code = typeof error.code === 'number' ? error.code : 7006
    this.message = error.message || `Failed to exchange OAuth credentials`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, OAuthErrorError.prototype)
  }
}

export class AccessErrorError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'AccessError'
    this.code = typeof error.code === 'number' ? error.code : 7007
    this.message = error.message || `Access error`
    this.status = typeof error.status === 'number' ? error.status : 401
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, AccessErrorError.prototype)
  }
}


export enum errors {
  WebrpcEndpoint = 'WebrpcEndpoint',
  WebrpcRequestFailed = 'WebrpcRequestFailed',
  WebrpcBadRoute = 'WebrpcBadRoute',
  WebrpcBadMethod = 'WebrpcBadMethod',
  WebrpcBadRequest = 'WebrpcBadRequest',
  WebrpcBadResponse = 'WebrpcBadResponse',
  WebrpcServerPanic = 'WebrpcServerPanic',
  WebrpcInternalError = 'WebrpcInternalError',
  WebrpcClientAborted = 'WebrpcClientAborted',
  WebrpcStreamLost = 'WebrpcStreamLost',
  WebrpcStreamFinished = 'WebrpcStreamFinished',
  InternalError = 'InternalError',
  EncryptionError = 'EncryptionError',
  DatabaseError = 'DatabaseError',
  DataIntegrityError = 'DataIntegrityError',
  IdentityProviderError = 'IdentityProviderError',
  InvalidRequest = 'InvalidRequest',
  InvalidSignature = 'InvalidSignature',
  KeyNotFound = 'KeyNotFound',
  KeyExpired = 'KeyExpired',
  SignerNotFound = 'SignerNotFound',
  UsageLimitExceeded = 'UsageLimitExceeded',
  PreconditionFailed = 'PreconditionFailed',
  ProofVerificationFailed = 'ProofVerificationFailed',
  AnswerIncorrect = 'AnswerIncorrect',
  ChallengeExpired = 'ChallengeExpired',
  TooManyAttempts = 'TooManyAttempts',
  OAuthError = 'OAuthError',
  AccessError = 'AccessError',
}

export enum WebrpcErrorCodes {
  WebrpcEndpoint = 0,
  WebrpcRequestFailed = -1,
  WebrpcBadRoute = -2,
  WebrpcBadMethod = -3,
  WebrpcBadRequest = -4,
  WebrpcBadResponse = -5,
  WebrpcServerPanic = -6,
  WebrpcInternalError = -7,
  WebrpcClientAborted = -8,
  WebrpcStreamLost = -9,
  WebrpcStreamFinished = -10,
  InternalError = 7100,
  EncryptionError = 7101,
  DatabaseError = 7102,
  DataIntegrityError = 7103,
  IdentityProviderError = 7104,
  InvalidRequest = 7200,
  InvalidSignature = 7201,
  KeyNotFound = 7202,
  KeyExpired = 7203,
  SignerNotFound = 7204,
  UsageLimitExceeded = 7205,
  PreconditionFailed = 7206,
  ProofVerificationFailed = 7002,
  AnswerIncorrect = 7003,
  ChallengeExpired = 7004,
  TooManyAttempts = 7005,
  OAuthError = 7006,
  AccessError = 7007,
}

export const webrpcErrorByCode: { [code: number]: any } = {
  [0]: WebrpcEndpointError,
  [-1]: WebrpcRequestFailedError,
  [-2]: WebrpcBadRouteError,
  [-3]: WebrpcBadMethodError,
  [-4]: WebrpcBadRequestError,
  [-5]: WebrpcBadResponseError,
  [-6]: WebrpcServerPanicError,
  [-7]: WebrpcInternalErrorError,
  [-8]: WebrpcClientAbortedError,
  [-9]: WebrpcStreamLostError,
  [-10]: WebrpcStreamFinishedError,
  [7100]: InternalErrorError,
  [7101]: EncryptionErrorError,
  [7102]: DatabaseErrorError,
  [7103]: DataIntegrityErrorError,
  [7104]: IdentityProviderErrorError,
  [7200]: InvalidRequestError,
  [7201]: InvalidSignatureError,
  [7202]: KeyNotFoundError,
  [7203]: KeyExpiredError,
  [7204]: SignerNotFoundError,
  [7205]: UsageLimitExceededError,
  [7206]: PreconditionFailedError,
  [7002]: ProofVerificationFailedError,
  [7003]: AnswerIncorrectError,
  [7004]: ChallengeExpiredError,
  [7005]: TooManyAttemptsError,
  [7006]: OAuthErrorError,
  [7007]: AccessErrorError,
}



//
// Webrpc
//

export const WebrpcHeader = "Webrpc"

export const WebrpcHeaderValue = "webrpc@v0.31.2;gen-typescript@v0.23.1;identity-instrument@v0.1.0"

type WebrpcGenVersions = {
  WebrpcGenVersion: string;
  codeGenName: string;
  codeGenVersion: string;
  schemaName: string;
  schemaVersion: string;
};

export function VersionFromHeader(headers: Headers): WebrpcGenVersions {
  const headerValue = headers.get(WebrpcHeader)
  if (!headerValue) {
    return {
      WebrpcGenVersion: "",
      codeGenName: "",
      codeGenVersion: "",
      schemaName: "",
      schemaVersion: "",
    };
  }

  return parseWebrpcGenVersions(headerValue)
}

function parseWebrpcGenVersions(header: string): WebrpcGenVersions {
  const versions = header.split(";")
  if (versions.length < 3) {
    return {
      WebrpcGenVersion: "",
      codeGenName: "",
      codeGenVersion: "",
      schemaName: "",
      schemaVersion: "",
    };
  }

  const [_, WebrpcGenVersion] = versions[0]!.split("@")
  const [codeGenName, codeGenVersion] = versions[1]!.split("@")
  const [schemaName, schemaVersion] = versions[2]!.split("@")

  return {
    WebrpcGenVersion: WebrpcGenVersion ?? "",
    codeGenName: codeGenName ?? "",
    codeGenVersion: codeGenVersion ?? "",
    schemaName: schemaName ?? "",
    schemaVersion: schemaVersion ?? "",
  };
}

