// identity-instrument v0.1.0 687d5663a6910014153890b5234adf350a81450d
// --
// Code generated by webrpc-gen@v0.23.1 with golang generator. DO NOT EDIT.
//
// webrpc-gen -schema=identity-instrument.ridl -target=golang -pkg=proto -server -client -out=./identity-instrument.gen.go
package proto

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

const WebrpcHeader = "Webrpc"

const WebrpcHeaderValue = "webrpc@v0.23.1;gen-golang@v0.17.0;identity-instrument@v0.1.0"

// WebRPC description and code-gen version
func WebRPCVersion() string {
	return "v1"
}

// Schema version of your RIDL schema
func WebRPCSchemaVersion() string {
	return "v0.1.0"
}

// Schema hash generated from your RIDL schema
func WebRPCSchemaHash() string {
	return "687d5663a6910014153890b5234adf350a81450d"
}

type WebrpcGenVersions struct {
	WebrpcGenVersion string
	CodeGenName      string
	CodeGenVersion   string
	SchemaName       string
	SchemaVersion    string
}

func VersionFromHeader(h http.Header) (*WebrpcGenVersions, error) {
	if h.Get(WebrpcHeader) == "" {
		return nil, fmt.Errorf("header is empty or missing")
	}

	versions, err := parseWebrpcGenVersions(h.Get(WebrpcHeader))
	if err != nil {
		return nil, fmt.Errorf("webrpc header is invalid: %w", err)
	}

	return versions, nil
}

func parseWebrpcGenVersions(header string) (*WebrpcGenVersions, error) {
	versions := strings.Split(header, ";")
	if len(versions) < 3 {
		return nil, fmt.Errorf("expected at least 3 parts while parsing webrpc header: %v", header)
	}

	_, webrpcGenVersion, ok := strings.Cut(versions[0], "@")
	if !ok {
		return nil, fmt.Errorf("webrpc gen version could not be parsed from: %s", versions[0])
	}

	tmplTarget, tmplVersion, ok := strings.Cut(versions[1], "@")
	if !ok {
		return nil, fmt.Errorf("tmplTarget and tmplVersion could not be parsed from: %s", versions[1])
	}

	schemaName, schemaVersion, ok := strings.Cut(versions[2], "@")
	if !ok {
		return nil, fmt.Errorf("schema name and schema version could not be parsed from: %s", versions[2])
	}

	return &WebrpcGenVersions{
		WebrpcGenVersion: webrpcGenVersion,
		CodeGenName:      tmplTarget,
		CodeGenVersion:   tmplVersion,
		SchemaName:       schemaName,
		SchemaVersion:    schemaVersion,
	}, nil
}

//
// Common types
//

type KeyType string

const (
	KeyType_Secp256k1 KeyType = "Secp256k1"
	KeyType_Secp256r1 KeyType = "Secp256r1"
)

func (x KeyType) MarshalText() ([]byte, error) {
	return []byte(x), nil
}

func (x *KeyType) UnmarshalText(b []byte) error {
	*x = KeyType(string(b))
	return nil
}

func (x *KeyType) Is(values ...KeyType) bool {
	if x == nil {
		return false
	}
	for _, v := range values {
		if *x == v {
			return true
		}
	}
	return false
}

type IdentityType string

const (
	IdentityType_Guest IdentityType = "Guest"
	IdentityType_Email IdentityType = "Email"
	IdentityType_OIDC  IdentityType = "OIDC"
)

func (x IdentityType) MarshalText() ([]byte, error) {
	return []byte(x), nil
}

func (x *IdentityType) UnmarshalText(b []byte) error {
	*x = IdentityType(string(b))
	return nil
}

func (x *IdentityType) Is(values ...IdentityType) bool {
	if x == nil {
		return false
	}
	for _, v := range values {
		if *x == v {
			return true
		}
	}
	return false
}

type AuthMode string

const (
	AuthMode_Guest        AuthMode = "Guest"
	AuthMode_OTP          AuthMode = "OTP"
	AuthMode_IDToken      AuthMode = "IDToken"
	AuthMode_AccessToken  AuthMode = "AccessToken"
	AuthMode_AuthCode     AuthMode = "AuthCode"
	AuthMode_AuthCodePKCE AuthMode = "AuthCodePKCE"
)

func (x AuthMode) MarshalText() ([]byte, error) {
	return []byte(x), nil
}

func (x *AuthMode) UnmarshalText(b []byte) error {
	*x = AuthMode(string(b))
	return nil
}

func (x *AuthMode) Is(values ...AuthMode) bool {
	if x == nil {
		return false
	}
	for _, v := range values {
		if *x == v {
			return true
		}
	}
	return false
}

type CommitVerifierParams struct {
	Scope        Scope             `json:"scope"`
	AuthKey      Key               `json:"authKey"`
	IdentityType IdentityType      `json:"identityType"`
	AuthMode     AuthMode          `json:"authMode"`
	Metadata     map[string]string `json:"metadata"`
	Handle       string            `json:"handle"`
	Signer       *Key              `json:"signer"`
}

type CompleteAuthParams struct {
	Scope        Scope        `json:"scope"`
	AuthKey      Key          `json:"authKey"`
	IdentityType IdentityType `json:"identityType"`
	SignerType   KeyType      `json:"signerType"`
	AuthMode     AuthMode     `json:"authMode"`
	Verifier     string       `json:"verifier"`
	Answer       string       `json:"answer"`
}

type SignParams struct {
	Scope     Scope  `json:"scope"`
	Signer    Key    `json:"signer"`
	Digest    string `json:"digest"`
	AuthKey   Key    `json:"authKey"`
	Signature string `json:"signature"`
}

type Identity struct {
	Type    IdentityType `json:"type"`
	Issuer  string       `json:"iss,omitempty"`
	Subject string       `json:"sub,omitempty"`
	Email   string       `json:"email,omitempty"`
}

type Key struct {
	KeyType KeyType `json:"keyType"`
	Address string  `json:"address"`
}

type AuthID struct {
	Scope        Scope        `json:"scope"`
	AuthMode     AuthMode     `json:"authMode"`
	IdentityType IdentityType `json:"identityType"`
	Verifier     string       `json:"verifier"`
}

type AuthKeyData struct {
	Scope   Scope     `json:"scope"`
	AuthKey Key       `json:"authKey"`
	Signer  Key       `json:"signer"`
	Expiry  time.Time `json:"expiry"`
}

type SignerData struct {
	Scope      Scope     `json:"scope"`
	Identity   *Identity `json:"identity"`
	KeyType    KeyType   `json:"keyType"`
	PrivateKey string    `json:"privateKey"`
}

type AuthCommitmentData struct {
	Scope        Scope             `json:"scope"`
	AuthKey      Key               `json:"authKey"`
	AuthMode     AuthMode          `json:"authMode"`
	IdentityType IdentityType      `json:"identityType"`
	Handle       string            `json:"handle"`
	Signer       Key               `json:"signer,omitempty"`
	Challenge    string            `json:"challenge"`
	Answer       string            `json:"answer"`
	Metadata     map[string]string `json:"metadata"`
	Attempts     uint              `json:"attempts"`
	Expiry       time.Time         `json:"expiry"`
}

var methods = map[string]method{
	"/rpc/IdentityInstrument/CommitVerifier": {
		Name:        "CommitVerifier",
		Service:     "IdentityInstrument",
		Annotations: map[string]string{},
	},
	"/rpc/IdentityInstrument/CompleteAuth": {
		Name:        "CompleteAuth",
		Service:     "IdentityInstrument",
		Annotations: map[string]string{},
	},
	"/rpc/IdentityInstrument/Sign": {
		Name:        "Sign",
		Service:     "IdentityInstrument",
		Annotations: map[string]string{},
	},
}

func WebrpcMethods() map[string]method {
	res := make(map[string]method, len(methods))
	for k, v := range methods {
		res[k] = v
	}

	return res
}

var WebRPCServices = map[string][]string{
	"IdentityInstrument": {
		"CommitVerifier",
		"CompleteAuth",
		"Sign",
	},
}

//
// Server types
//

type IdentityInstrument interface {
	CommitVerifier(ctx context.Context, params *CommitVerifierParams) (string, string, string, error)
	CompleteAuth(ctx context.Context, params *CompleteAuthParams) (*Key, error)
	Sign(ctx context.Context, params *SignParams) (string, error)
}

//
// Client types
//

type IdentityInstrumentClient interface {
	CommitVerifier(ctx context.Context, params *CommitVerifierParams) (string, string, string, error)
	CompleteAuth(ctx context.Context, params *CompleteAuthParams) (*Key, error)
	Sign(ctx context.Context, params *SignParams) (string, error)
}

//
// Server
//

type WebRPCServer interface {
	http.Handler
}

type identityInstrumentServer struct {
	IdentityInstrument
	OnError   func(r *http.Request, rpcErr *WebRPCError)
	OnRequest func(w http.ResponseWriter, r *http.Request) error
}

func NewIdentityInstrumentServer(svc IdentityInstrument) *identityInstrumentServer {
	return &identityInstrumentServer{
		IdentityInstrument: svc,
	}
}

func (s *identityInstrumentServer) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	defer func() {
		// In case of a panic, serve a HTTP 500 error and then panic.
		if rr := recover(); rr != nil {
			s.sendErrorJSON(w, r, ErrWebrpcServerPanic.WithCausef("%v", rr))
			panic(rr)
		}
	}()

	w.Header().Set(WebrpcHeader, WebrpcHeaderValue)

	ctx := r.Context()
	ctx = context.WithValue(ctx, HTTPResponseWriterCtxKey, w)
	ctx = context.WithValue(ctx, HTTPRequestCtxKey, r)
	ctx = context.WithValue(ctx, ServiceNameCtxKey, "IdentityInstrument")

	r = r.WithContext(ctx)

	var handler func(ctx context.Context, w http.ResponseWriter, r *http.Request)
	switch r.URL.Path {
	case "/rpc/IdentityInstrument/CommitVerifier":
		handler = s.serveCommitVerifierJSON
	case "/rpc/IdentityInstrument/CompleteAuth":
		handler = s.serveCompleteAuthJSON
	case "/rpc/IdentityInstrument/Sign":
		handler = s.serveSignJSON
	default:
		err := ErrWebrpcBadRoute.WithCausef("no webrpc method defined for path %v", r.URL.Path)
		s.sendErrorJSON(w, r, err)
		return
	}

	if r.Method != "POST" {
		w.Header().Add("Allow", "POST") // RFC 9110.
		err := ErrWebrpcBadMethod.WithCausef("unsupported HTTP method %v (only POST is allowed)", r.Method)
		s.sendErrorJSON(w, r, err)
		return
	}

	contentType := r.Header.Get("Content-Type")
	if i := strings.Index(contentType, ";"); i >= 0 {
		contentType = contentType[:i]
	}
	contentType = strings.TrimSpace(strings.ToLower(contentType))

	switch contentType {
	case "application/json":
		if s.OnRequest != nil {
			if err := s.OnRequest(w, r); err != nil {
				rpcErr, ok := err.(WebRPCError)
				if !ok {
					rpcErr = ErrWebrpcEndpoint.WithCause(err)
				}
				s.sendErrorJSON(w, r, rpcErr)
				return
			}
		}

		handler(ctx, w, r)
	default:
		err := ErrWebrpcBadRequest.WithCausef("unsupported Content-Type %q (only application/json is allowed)", r.Header.Get("Content-Type"))
		s.sendErrorJSON(w, r, err)
	}
}

func (s *identityInstrumentServer) serveCommitVerifierJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "CommitVerifier")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 *CommitVerifierParams `json:"params"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, ret1, ret2, err := s.IdentityInstrument.CommitVerifier(ctx, reqPayload.Arg0)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 string `json:"verifier"`
		Ret1 string `json:"loginHint"`
		Ret2 string `json:"challenge"`
	}{ret0, ret1, ret2}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *identityInstrumentServer) serveCompleteAuthJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "CompleteAuth")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 *CompleteAuthParams `json:"params"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, err := s.IdentityInstrument.CompleteAuth(ctx, reqPayload.Arg0)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 *Key `json:"signer"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *identityInstrumentServer) serveSignJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "Sign")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 *SignParams `json:"params"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, err := s.IdentityInstrument.Sign(ctx, reqPayload.Arg0)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 string `json:"signature"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *identityInstrumentServer) sendErrorJSON(w http.ResponseWriter, r *http.Request, rpcErr WebRPCError) {
	if s.OnError != nil {
		s.OnError(r, &rpcErr)
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(rpcErr.HTTPStatus)

	respBody, _ := json.Marshal(rpcErr)
	w.Write(respBody)
}

func RespondWithError(w http.ResponseWriter, err error) {
	rpcErr, ok := err.(WebRPCError)
	if !ok {
		rpcErr = ErrWebrpcEndpoint.WithCause(err)
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(rpcErr.HTTPStatus)

	respBody, _ := json.Marshal(rpcErr)
	w.Write(respBody)
}

//
// Client
//

const IdentityInstrumentPathPrefix = "/rpc/IdentityInstrument/"

type identityInstrumentClient struct {
	client HTTPClient
	urls   [3]string
}

func NewIdentityInstrumentClient(addr string, client HTTPClient) IdentityInstrumentClient {
	prefix := urlBase(addr) + IdentityInstrumentPathPrefix
	urls := [3]string{
		prefix + "CommitVerifier",
		prefix + "CompleteAuth",
		prefix + "Sign",
	}
	return &identityInstrumentClient{
		client: client,
		urls:   urls,
	}
}

func (c *identityInstrumentClient) CommitVerifier(ctx context.Context, params *CommitVerifierParams) (string, string, string, error) {
	in := struct {
		Arg0 *CommitVerifierParams `json:"params"`
	}{params}
	out := struct {
		Ret0 string `json:"verifier"`
		Ret1 string `json:"loginHint"`
		Ret2 string `json:"challenge"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[0], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, out.Ret1, out.Ret2, err
}

func (c *identityInstrumentClient) CompleteAuth(ctx context.Context, params *CompleteAuthParams) (*Key, error) {
	in := struct {
		Arg0 *CompleteAuthParams `json:"params"`
	}{params}
	out := struct {
		Ret0 *Key `json:"signer"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[1], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

func (c *identityInstrumentClient) Sign(ctx context.Context, params *SignParams) (string, error) {
	in := struct {
		Arg0 *SignParams `json:"params"`
	}{params}
	out := struct {
		Ret0 string `json:"signature"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[2], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

// HTTPClient is the interface used by generated clients to send HTTP requests.
// It is fulfilled by *(net/http).Client, which is sufficient for most users.
// Users can provide their own implementation for special retry policies.
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// urlBase helps ensure that addr specifies a scheme. If it is unparsable
// as a URL, it returns addr unchanged.
func urlBase(addr string) string {
	// If the addr specifies a scheme, use it. If not, default to
	// http. If url.Parse fails on it, return it unchanged.
	url, err := url.Parse(addr)
	if err != nil {
		return addr
	}
	if url.Scheme == "" {
		url.Scheme = "http"
	}
	return url.String()
}

// newRequest makes an http.Request from a client, adding common headers.
func newRequest(ctx context.Context, url string, reqBody io.Reader, contentType string) (*http.Request, error) {
	req, err := http.NewRequestWithContext(ctx, "POST", url, reqBody)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Accept", contentType)
	req.Header.Set("Content-Type", contentType)
	req.Header.Set(WebrpcHeader, WebrpcHeaderValue)
	if headers, ok := HTTPRequestHeaders(ctx); ok {
		for k := range headers {
			for _, v := range headers[k] {
				req.Header.Add(k, v)
			}
		}
	}
	return req, nil
}

// doHTTPRequest is common code to make a request to the remote service.
func doHTTPRequest(ctx context.Context, client HTTPClient, url string, in, out interface{}) (*http.Response, error) {
	reqBody, err := json.Marshal(in)
	if err != nil {
		return nil, ErrWebrpcRequestFailed.WithCausef("failed to marshal JSON body: %w", err)
	}
	if err = ctx.Err(); err != nil {
		return nil, ErrWebrpcRequestFailed.WithCausef("aborted because context was done: %w", err)
	}

	req, err := newRequest(ctx, url, bytes.NewBuffer(reqBody), "application/json")
	if err != nil {
		return nil, ErrWebrpcRequestFailed.WithCausef("could not build request: %w", err)
	}

	resp, err := client.Do(req)
	if err != nil {
		return nil, ErrWebrpcRequestFailed.WithCause(err)
	}

	if resp.StatusCode != 200 {
		respBody, err := io.ReadAll(resp.Body)
		if err != nil {
			return nil, ErrWebrpcBadResponse.WithCausef("failed to read server error response body: %w", err)
		}

		var rpcErr WebRPCError
		if err := json.Unmarshal(respBody, &rpcErr); err != nil {
			return nil, ErrWebrpcBadResponse.WithCausef("failed to unmarshal server error: %w", err)
		}
		if rpcErr.Cause != "" {
			rpcErr.cause = errors.New(rpcErr.Cause)
		}
		return nil, rpcErr
	}

	if out != nil {
		respBody, err := io.ReadAll(resp.Body)
		if err != nil {
			return nil, ErrWebrpcBadResponse.WithCausef("failed to read response body: %w", err)
		}

		err = json.Unmarshal(respBody, &out)
		if err != nil {
			return nil, ErrWebrpcBadResponse.WithCausef("failed to unmarshal JSON response body: %w", err)
		}
	}

	return resp, nil
}

func WithHTTPRequestHeaders(ctx context.Context, h http.Header) (context.Context, error) {
	if _, ok := h["Accept"]; ok {
		return nil, errors.New("provided header cannot set Accept")
	}
	if _, ok := h["Content-Type"]; ok {
		return nil, errors.New("provided header cannot set Content-Type")
	}

	copied := make(http.Header, len(h))
	for k, vv := range h {
		if vv == nil {
			copied[k] = nil
			continue
		}
		copied[k] = make([]string, len(vv))
		copy(copied[k], vv)
	}

	return context.WithValue(ctx, HTTPClientRequestHeadersCtxKey, copied), nil
}

func HTTPRequestHeaders(ctx context.Context) (http.Header, bool) {
	h, ok := ctx.Value(HTTPClientRequestHeadersCtxKey).(http.Header)
	return h, ok
}

//
// Helpers
//

type method struct {
	Name        string
	Service     string
	Annotations map[string]string
}

type contextKey struct {
	name string
}

func (k *contextKey) String() string {
	return "webrpc context value " + k.name
}

var (
	HTTPClientRequestHeadersCtxKey = &contextKey{"HTTPClientRequestHeaders"}
	HTTPResponseWriterCtxKey       = &contextKey{"HTTPResponseWriter"}

	HTTPRequestCtxKey = &contextKey{"HTTPRequest"}

	ServiceNameCtxKey = &contextKey{"ServiceName"}

	MethodNameCtxKey = &contextKey{"MethodName"}
)

func ServiceNameFromContext(ctx context.Context) string {
	service, _ := ctx.Value(ServiceNameCtxKey).(string)
	return service
}

func MethodNameFromContext(ctx context.Context) string {
	method, _ := ctx.Value(MethodNameCtxKey).(string)
	return method
}

func RequestFromContext(ctx context.Context) *http.Request {
	r, _ := ctx.Value(HTTPRequestCtxKey).(*http.Request)
	return r
}

func MethodCtx(ctx context.Context) (method, bool) {
	req := RequestFromContext(ctx)
	if req == nil {
		return method{}, false
	}

	m, ok := methods[req.URL.Path]
	if !ok {
		return method{}, false
	}

	return m, true
}

func ResponseWriterFromContext(ctx context.Context) http.ResponseWriter {
	w, _ := ctx.Value(HTTPResponseWriterCtxKey).(http.ResponseWriter)
	return w
}

//
// Errors
//

type WebRPCError struct {
	Name       string `json:"error"`
	Code       int    `json:"code"`
	Message    string `json:"msg"`
	Cause      string `json:"cause,omitempty"`
	HTTPStatus int    `json:"status"`
	cause      error
}

var _ error = WebRPCError{}

func (e WebRPCError) Error() string {
	if e.cause != nil {
		return fmt.Sprintf("%s %d: %s: %v", e.Name, e.Code, e.Message, e.cause)
	}
	return fmt.Sprintf("%s %d: %s", e.Name, e.Code, e.Message)
}

func (e WebRPCError) Is(target error) bool {
	if target == nil {
		return false
	}
	if rpcErr, ok := target.(WebRPCError); ok {
		return rpcErr.Code == e.Code
	}
	return errors.Is(e.cause, target)
}

func (e WebRPCError) Unwrap() error {
	return e.cause
}

func (e WebRPCError) WithCause(cause error) WebRPCError {
	err := e
	err.cause = cause
	err.Cause = cause.Error()
	return err
}

func (e WebRPCError) WithCausef(format string, args ...interface{}) WebRPCError {
	cause := fmt.Errorf(format, args...)
	err := e
	err.cause = cause
	err.Cause = cause.Error()
	return err
}

// Deprecated: Use .WithCause() method on WebRPCError.
func ErrorWithCause(rpcErr WebRPCError, cause error) WebRPCError {
	return rpcErr.WithCause(cause)
}

// Webrpc errors
var (
	ErrWebrpcEndpoint           = WebRPCError{Code: 0, Name: "WebrpcEndpoint", Message: "endpoint error", HTTPStatus: 400}
	ErrWebrpcRequestFailed      = WebRPCError{Code: -1, Name: "WebrpcRequestFailed", Message: "request failed", HTTPStatus: 400}
	ErrWebrpcBadRoute           = WebRPCError{Code: -2, Name: "WebrpcBadRoute", Message: "bad route", HTTPStatus: 404}
	ErrWebrpcBadMethod          = WebRPCError{Code: -3, Name: "WebrpcBadMethod", Message: "bad method", HTTPStatus: 405}
	ErrWebrpcBadRequest         = WebRPCError{Code: -4, Name: "WebrpcBadRequest", Message: "bad request", HTTPStatus: 400}
	ErrWebrpcBadResponse        = WebRPCError{Code: -5, Name: "WebrpcBadResponse", Message: "bad response", HTTPStatus: 500}
	ErrWebrpcServerPanic        = WebRPCError{Code: -6, Name: "WebrpcServerPanic", Message: "server panic", HTTPStatus: 500}
	ErrWebrpcInternalError      = WebRPCError{Code: -7, Name: "WebrpcInternalError", Message: "internal error", HTTPStatus: 500}
	ErrWebrpcClientDisconnected = WebRPCError{Code: -8, Name: "WebrpcClientDisconnected", Message: "client disconnected", HTTPStatus: 400}
	ErrWebrpcStreamLost         = WebRPCError{Code: -9, Name: "WebrpcStreamLost", Message: "stream lost", HTTPStatus: 400}
	ErrWebrpcStreamFinished     = WebRPCError{Code: -10, Name: "WebrpcStreamFinished", Message: "stream finished", HTTPStatus: 200}
)

// Schema errors
var (
	ErrInternalError           = WebRPCError{Code: 7100, Name: "InternalError", Message: "Internal error", HTTPStatus: 500}
	ErrEncryptionError         = WebRPCError{Code: 7101, Name: "EncryptionError", Message: "Encryption error", HTTPStatus: 500}
	ErrDatabaseError           = WebRPCError{Code: 7102, Name: "DatabaseError", Message: "Database error", HTTPStatus: 500}
	ErrDataIntegrityError      = WebRPCError{Code: 7103, Name: "DataIntegrityError", Message: "Data integrity error", HTTPStatus: 500}
	ErrIdentityProviderError   = WebRPCError{Code: 7104, Name: "IdentityProviderError", Message: "Identity provider error", HTTPStatus: 500}
	ErrInvalidRequest          = WebRPCError{Code: 7200, Name: "InvalidRequest", Message: "The request was invalid", HTTPStatus: 400}
	ErrInvalidSignature        = WebRPCError{Code: 7201, Name: "InvalidSignature", Message: "The signature was invalid", HTTPStatus: 400}
	ErrKeyNotFound             = WebRPCError{Code: 7202, Name: "KeyNotFound", Message: "The authentication key was not found", HTTPStatus: 404}
	ErrKeyExpired              = WebRPCError{Code: 7203, Name: "KeyExpired", Message: "The authentication key expired", HTTPStatus: 400}
	ErrSignerNotFound          = WebRPCError{Code: 7204, Name: "SignerNotFound", Message: "The signer was not found", HTTPStatus: 404}
	ErrProofVerificationFailed = WebRPCError{Code: 7002, Name: "ProofVerificationFailed", Message: "The authentication proof could not be verified", HTTPStatus: 400}
	ErrAnswerIncorrect         = WebRPCError{Code: 7003, Name: "AnswerIncorrect", Message: "The provided answer is incorrect", HTTPStatus: 400}
	ErrChallengeExpired        = WebRPCError{Code: 7004, Name: "ChallengeExpired", Message: "The challenge has expired", HTTPStatus: 400}
	ErrTooManyAttempts         = WebRPCError{Code: 7005, Name: "TooManyAttempts", Message: "Too many attempts", HTTPStatus: 400}
)
